import type { Metadata } from "next";

import { Providers } from "@/lib/Providers";
import ApolloWrapper from "@/lib/graphql/apollo-wrapper";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloWrapper>
        <Providers>
          <body className={inter.className}>{children}</body>
        </Providers>
      </ApolloWrapper>
    </html>
  );
}
