"use client";

import DrawerDialog from "@/components/drawer-dialog";
import { Button } from "@nextui-org/button";
import { useState } from "react";
import AddUserForm from "@/app/_forms/add-user-form-auto/form";

export default function AddUserAutoModal() {
  const openState = useState(false);

  return (
      <DrawerDialog
        openState={openState}
        openTrigger={<Button>Add User autogenerated mutation</Button>}
        title={"Add User with auto generated mutation"}
      >
        <>
          <AddUserForm openState={openState} />
        </>
      </DrawerDialog>
  );
}
